-- ============================================================================
-- 0012_service_image.sql — SUPERSEDED by 0029_business_page.sql (M20).
-- ----------------------------------------------------------------------------
-- This file USED to add `services.image_url` (M11.2): an optional column holding
-- either an http(s) URL or a client-resized `data:` URL for a service card
-- picture. M20 replaced that feature with the business-page gallery
-- (`business_images` + files on disk), and 0029 DROPs the column for good —
-- Omer's decision, 2026-07-21 (see docs/decisions/0028-m20-business-page.md).
--
-- WHY THE BODY IS GONE RATHER THAN THE FILE:
-- the migration runner has no ledger — it replays EVERY file in this directory
-- on every boot, in filename order. Leaving the ALTER here would have re-ADDed
-- the column on each start, and the end state would have been correct only by
-- the accident that 0029 sorts after 0012. That is a trap, not a design. The
-- file itself stays so the numbering never shifts and old logs still line up.
--
-- Nothing to run. Do not add statements here — write a new numbered migration.
-- ============================================================================
